import type { Employee } from "@/types/employee"

export const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "John Smith",
    role: "Driver",
    profileScore: 25,
    riskLevel: "High",
    issues: ["Failed drug test", "Multiple driving violations", "Fake license detected", "Poor customer ratings"],
    details: {
      drivingViolationRecords: 8,
      drugTestResults: "Positive",
      licenseVerification: "Fake",
      warehouseIncidentInvolvement: true,
      riderCustomerRatings: 2.1,
      breathalyzerResults: "Fail",
      recklessDrivingPatterns: true,
      drivingWorkViolations: 5,
      workPerformanceFeedback: 1.8,
      warehouseInfractions: 3,
      credentialValidity: "Fake",
    },
  },
  {
    id: "2",
    name: "Sarah Johnson",
    role: "Mechanic",
    profileScore: 85,
    riskLevel: "Low",
    issues: [],
    details: {
      certificationsValidID: "Valid",
      repairLogsRepeatFixRate: 5,
      downtimePostMaintenance: 8,
      peerInternalReviews: 4.8,
      equipmentHandlingViolations: 0,
    },
  },
  {
    id: "3",
    name: "Mike Davis",
    role: "Driver",
    profileScore: 65,
    riskLevel: "Medium",
    issues: ["Below average customer rating", "Minor warehouse infractions"],
    details: {
      drivingViolationRecords: 2,
      drugTestResults: "Negative",
      licenseVerification: "Valid",
      warehouseIncidentInvolvement: false,
      riderCustomerRatings: 3.2,
      breathalyzerResults: "Pass",
      recklessDrivingPatterns: false,
      drivingWorkViolations: 1,
      workPerformanceFeedback: 3.5,
      warehouseInfractions: 2,
      credentialValidity: "Valid",
    },
  },
  {
    id: "4",
    name: "Lisa Chen",
    role: "Helper",
    profileScore: 78,
    riskLevel: "Low",
    issues: [],
    details: {
      submittedIDsDocuments: "Valid",
      missedDeliveries: 2,
      warehouseMismanagement: 1,
      behaviorReports: 0,
    },
  },
  {
    id: "5",
    name: "Robert Wilson",
    role: "Mechanic",
    profileScore: 45,
    riskLevel: "High",
    issues: ["High repeat fix rate", "Poor peer reviews", "Equipment handling violations"],
    details: {
      certificationsValidID: "Valid",
      repairLogsRepeatFixRate: 28,
      downtimePostMaintenance: 45,
      peerInternalReviews: 2.1,
      equipmentHandlingViolations: 4,
    },
  },
  {
    id: "6",
    name: "Emily Brown",
    role: "Driver",
    profileScore: 92,
    riskLevel: "Low",
    issues: [],
    details: {
      drivingViolationRecords: 0,
      drugTestResults: "Negative",
      licenseVerification: "Valid",
      warehouseIncidentInvolvement: false,
      riderCustomerRatings: 4.8,
      breathalyzerResults: "Pass",
      recklessDrivingPatterns: false,
      drivingWorkViolations: 0,
      workPerformanceFeedback: 4.9,
      warehouseInfractions: 0,
      credentialValidity: "Valid",
    },
  },
  {
    id: "7",
    name: "David Martinez",
    role: "Helper",
    profileScore: 35,
    riskLevel: "High",
    issues: ["Missing documentation", "High missed deliveries", "Multiple behavior reports"],
    details: {
      submittedIDsDocuments: "Missing",
      missedDeliveries: 12,
      warehouseMismanagement: 8,
      behaviorReports: 6,
    },
  },
  {
    id: "8",
    name: "Amanda Taylor",
    role: "Mechanic",
    profileScore: 72,
    riskLevel: "Medium",
    issues: ["Moderate repeat fix rate"],
    details: {
      certificationsValidID: "Valid",
      repairLogsRepeatFixRate: 18,
      downtimePostMaintenance: 22,
      peerInternalReviews: 3.8,
      equipmentHandlingViolations: 1,
    },
  },
  {
    id: "9",
    name: "Carlos Rodriguez",
    role: "Driver",
    profileScore: 58,
    riskLevel: "Medium",
    issues: ["Expired license", "Average performance feedback"],
    details: {
      drivingViolationRecords: 3,
      drugTestResults: "Negative",
      licenseVerification: "Expired",
      warehouseIncidentInvolvement: false,
      riderCustomerRatings: 3.8,
      breathalyzerResults: "Pass",
      recklessDrivingPatterns: false,
      drivingWorkViolations: 2,
      workPerformanceFeedback: 3.1,
      warehouseInfractions: 1,
      credentialValidity: "Expired",
    },
  },
  {
    id: "10",
    name: "Jennifer Lee",
    role: "Helper",
    profileScore: 88,
    riskLevel: "Low",
    issues: [],
    details: {
      submittedIDsDocuments: "Valid",
      missedDeliveries: 1,
      warehouseMismanagement: 0,
      behaviorReports: 0,
    },
  },
]
