"""Initial migration

Revision ID: 2af537f1ce35
Revises: 
Create Date: 2025-08-11 10:48:16.901603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af537f1ce35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=True),
    sa.Column('driving_violations', sa.Integer(), nullable=True),
    sa.Column('drug_test_result', sa.Enum('POSITIVE', 'NEGATIVE', name='drug_test_results'), nullable=True),
    sa.Column('license_validity', sa.Enum('VALID', 'EXPIRED', 'FAKE', name='validity'), nullable=True),
    sa.Column('incident_involvement', sa.Boolean(), nullable=True),
    sa.Column('breathalyzer_results', sa.Float(), nullable=True),
    sa.Column('dangerous_driving_patterns', sa.Boolean(), nullable=True),
    sa.Column('work_violations', sa.Integer(), nullable=True),
    sa.Column('performance_rating', sa.Float(), nullable=True),
    sa.Column('warehouse_infractions', sa.Integer(), nullable=True),
    sa.Column('document_validity', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('eval_results',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_type', sa.Enum('DRIVER', 'MECHANIC', 'HELPER', name='profile_type'), nullable=True),
    sa.Column('profile_score', sa.Integer(), nullable=True),
    sa.Column('issues_list', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('helper_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=True),
    sa.Column('id_credentials_validity', sa.Enum('VALID', 'EXPIRED', 'FAKE', name='validity'), nullable=True),
    sa.Column('missed_delivery_rates', sa.Integer(), nullable=True),
    sa.Column('mismanagement_records', sa.Integer(), nullable=True),
    sa.Column('behavior_reports_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('mechanic_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=True),
    sa.Column('id_cert_validity', sa.Enum('VALID', 'EXPIRED', 'FAKE', name='validity'), nullable=True),
    sa.Column('repair_rates', sa.Integer(), nullable=True),
    sa.Column('internal_review_score', sa.Float(), nullable=True),
    sa.Column('equipment_violations', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mechanic_profiles')
    op.drop_table('helper_profiles')
    op.drop_table('eval_results')
    op.drop_table('driver_profiles')
    # ### end Alembic commands ###
